### ISSUE TITLE
AnyProxy 3.8.0  is about to exit with code: 0

### ISSUE THREAD

**Issue by ayooay** [alibaba/anyproxy#41] opened 2015-11-18 11:09 UTC
Caught exception: RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at Function.Buffer.concat (buffer.js:234:16)
    at /usr/lib/node_modules/anyproxy/lib/requestHandler.js:178:52
    at /usr/lib/node_modules/anyproxy/node_modules/async/lib/async.js:607:21
    at /usr/lib/node_modules/anyproxy/node_modules/async/lib/async.js:246:17
    at iterate (/usr/lib/node_modules/anyproxy/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/usr/lib/node_modules/anyproxy/node_modules/async/lib/async.js:162:9)
AnyProxy is about to exit with code: 0

**Comment by oldashes** [comment] 2015-12-29 08:15
> % anyproxy --port 8003
the default rule for AnyProxy which supports CORS.
Anyproxy rules initialize finished, have fun!
GUI interface started at : http://192.168.1.102:8002/
Http proxy started at 192.168.1.102:8003
Caught exception: Error: listen EADDRINUSE :::8002
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at EventEmitter.listen (/usr/local/lib/node_modules/anyproxy/node_modules/express/lib/application.js:617:24)
    at /usr/local/lib/node_modules/anyproxy/lib/webInterface.js:145:26
    at Object.module.exports._plugIntoWebinterface (/usr/local/lib/node_modules/anyproxy/lib/rule_default.js:181:9)
    at new webInterface (/usr/local/lib/node_modules/anyproxy/lib/webInterface.js:144:18)
    at /usr/local/lib/node_modules/anyproxy/proxy.js:156:46
AnyProxy is about to exit with code: 0

**Comment by codingfishman** [comment] 2016-09-01 12:18
Hi @ayooay 
   **SORRY FOR THE BIG DELAY :(**.
   Do you still try the anyproxy? if the issue still happened, could you  help to point out when will the process exit, right after initialization?

**Comment by codingfishman** [comment] 2016-09-01 12:20
Hi @oldashes 
   ** SORRY, IT'S BEEN 8 MONTHES :(**
  Are you still using the Anyproxy? It seems the issue caused by the port conflict, which version were you work on then?

**Comment by codingfishman** [comment] 2017-11-22 07:21
Close the issue, will reopen if more discussions are joined.

**Closed by codingfishman** 2017-11-22 07:21 UTC
